train: ../train/images
val: ../valid/images
test: ../test/images

nc: 1
names: ['Licence-number']

roboflow:
  workspace: plate-detection-8sa0a
  project: car-plate-detection-vbivf
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/plate-detection-8sa0a/car-plate-detection-vbivf/dataset/2